import React from 'react';
import { useCalibration } from '../hooks/useCalibration';
import { getCalibratedValue } from '../utils/calibration';
import type { ProvenanceValue } from '../types/backend';

export function Calibration() {
    const calibration = useCalibration();

    if (!calibration) return <div style={{ padding: 16 }}>LOADING CALIBRATION VECTORS...</div>;

    const renderProvenance = (val: ProvenanceValue | undefined, fallback: string) => {
        if (!val) return <span className="data-value mono-num">{fallback}</span>;
        
        const isFault = val.quality_status !== 'ACCEPTED';
        const formattedVal = val.value.toFixed(4);
        
        return (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '2px' }}>
                <span className="data-value mono-num">{formattedVal}</span>
                <span style={{ fontSize: '9px', color: isFault ? 'var(--accent-red)' : 'var(--text-muted)' }}>
                    [{val.source}] {val.quality_status}
                </span>
            </div>
        );
    };

    return (
        <div style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div className="panel" style={{ borderLeft: '2px solid var(--accent-cyan)' }}>
                <div className="panel-header">CALIBRATION ENGINE (PHASE 5C)</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    Displaying global empirical priors generated by the robust regression pipeline.
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>DEGRADATION PRIORS (SEC/LAP)</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-red)' }}>SOFT</span>
                        {renderProvenance(calibration.degradation_slopes?.SOFT, "0.1000")}
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-amber)' }}>MEDIUM</span>
                        {renderProvenance(calibration.degradation_slopes?.MEDIUM, "0.0800")}
                    </div>
                    <div className="data-row">
                        <span className="data-label">HARD</span>
                        {renderProvenance(calibration.degradation_slopes?.HARD, "0.0600")}
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-green)' }}>INTERMEDIATE</span>
                        {renderProvenance(calibration.degradation_slopes?.INTERMEDIATE, "0.1200")}
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-blue)' }}>WET</span>
                        {renderProvenance(calibration.degradation_slopes?.WET, "0.1500")}
                    </div>
                </div>

                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>COMPOUND DELTAS (VS SOFT)</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-amber)' }}>MEDIUM DELTA</span>
                        {renderProvenance(calibration.compound_deltas?.MEDIUM, "0.7194")}
                    </div>
                    <div className="data-row">
                        <span className="data-label">HARD DELTA</span>
                        {renderProvenance(calibration.compound_deltas?.HARD, "0.5695")}
                    </div>
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>GLOBAL PIT-LOSS</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">TRANSIT CONSTANT</span>
                        {renderProvenance(calibration.pit_loss, "23.7500")}
                    </div>
                </div>
                
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px', borderLeft: '2px solid var(--accent-red)' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>FUEL BURN EFFECT</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">WEIGHT PENALTY</span>
                        {renderProvenance(calibration.fuel_burn_effect, "0.0600")}
                    </div>
                    <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '8px' }}>
                        * Fuel mass flow is not empirically observable from public telemetry.
                    </div>
                </div>
            </div>
        </div>
    );
}
