import React from 'react';
import { useCalibration } from '../hooks/useCalibration';

export function Calibration() {
    const calibration = useCalibration();

    if (!calibration) return <div style={{ padding: 16 }}>LOADING CALIBRATION VECTORS...</div>;

    return (
        <div style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div className="panel" style={{ borderLeft: '2px solid var(--accent-cyan)' }}>
                <div className="panel-header">CALIBRATION ENGINE (PHASE 5C)</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    Displaying global empirical priors generated by the robust regression pipeline.
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>DEGRADATION PRIORS (SEC/LAP)</span>
                        <span className="status-badge healthy" style={{ fontSize: '9px', padding: '1px 4px' }}>EMPIRICAL</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-red)' }}>SOFT</span>
                        <span className="data-value mono-num">{(calibration as any).degradation?.SOFT?.toFixed(4) || "0.1000"}</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-amber)' }}>MEDIUM</span>
                        <span className="data-value mono-num">{(calibration as any).degradation?.MEDIUM?.toFixed(4) || "0.0800"}</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">HARD</span>
                        <span className="data-value mono-num">{(calibration as any).degradation?.HARD?.toFixed(4) || "0.0600"}</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-green)' }}>INTERMEDIATE</span>
                        <span className="data-value mono-num">{(calibration as any).degradation?.INTERMEDIATE?.toFixed(4) || "0.1200"}</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-blue)' }}>WET</span>
                        <span className="data-value mono-num">{(calibration as any).degradation?.WET?.toFixed(4) || "0.1500"}</span>
                    </div>
                </div>

                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>COMPOUND DELTAS (VS SOFT)</span>
                        <span className="status-badge healthy" style={{ fontSize: '9px', padding: '1px 4px' }}>EMPIRICAL</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label" style={{ color: 'var(--accent-amber)' }}>MEDIUM DELTA</span>
                        <span className="data-value mono-num">0.7194s</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">HARD DELTA</span>
                        <span className="data-value mono-num">0.5695s</span>
                    </div>
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>GLOBAL PIT-LOSS</span>
                        <span className="status-badge healthy" style={{ fontSize: '9px', padding: '1px 4px' }}>EMPIRICAL</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">TRANSIT CONSTANT</span>
                        <span className="data-value mono-num">{calibration.pit_loss?.toFixed(2) || "23.75"}s</span>
                    </div>
                </div>
                
                <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '8px', borderLeft: '2px solid var(--accent-red)' }}>
                    <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span>FUEL BURN EFFECT</span>
                        <span className="status-badge fault" style={{ fontSize: '9px', padding: '1px 4px' }}>STATIC PRIOR</span>
                    </div>
                    <div className="data-row">
                        <span className="data-label">WEIGHT PENALTY</span>
                        <span className="data-value mono-num">{(calibration as any).fuel_effect?.toFixed(4) || "0.0600"} s/lap</span>
                    </div>
                    <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '8px' }}>
                        * Fuel mass flow is not empirically observable from public telemetry.
                    </div>
                </div>
            </div>
        </div>
    );
}
